11:42:25 AM: DEBUG [cursor_del_pool.py:10] Incio del método with __enter__
11:42:27 AM: ERROR [conexion.py:28] Ocurrió un error al obtener el pool could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

